---
name: Nagibot
version: 0.8
author: []
abstract: A XMPP robot for Nagios(tm) notifications and interaction.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  AnyEvent: 0
  AnyEvent::XMPP: < 0.6
  Nagios::Status::HostStatus: 0
  Nagios::Status::ServiceStatus: 0
  Sys::CpuLoad: 0
  YAML: 0
configure_requires:
  Module::Build: 0.35
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
